Add unattended mode for automated installs (especially for testing on VMs)

diff --git a/nix/installer/installer b/nix/installer/installer
--- a/nix/installer/installer
+++ b/nix/installer/installer
@@ -6,6 +6,7 @@ source "${RECORDS_SH:?}/records.sh"
 # shellcheck disable=SC2034
 LOGPROGRAM=install-nixos
 INSTALLTMP=/tmp/install-nixos
+UNATTENDEDPATH=/iso/unattended.json
 
 main() {
   DOC="install-nixos - Install NixOS on the current machine
@@ -18,7 +19,8 @@ Options:
   --no-update    Don't \`nix run\` \$UPDATEURL
   --no-sb-check  Don't check if the system is in Setup Mode
   --no-mount     Don't mount the host system flake source if available
-  --repourl=URL  Set the installation repository URL [default: \$REPOURL]
+  --unattended   Enable unattended mode, if /iso/unattended.json exists
+  --repourl=URL    Set the installation repository URL [default: \$REPOURL]
   --install-dev <DEVPATH>  Devicepath to install to
   --nixosconfig <CONFIG>   Name of nixosConfiguration to install
 "
@@ -26,26 +28,27 @@ Options:
 # shellcheck disable=2016,2086,2329,1090,1091,2034
 docopt() { local v='2.0.3'; source "${DOCOPT_LIB_SH:?}/docopt-lib.sh" "$v" || {
 ret=$?;printf -- "exit %d\n" "$ret";exit "$ret";};set -e
-trimmed_doc=${DOC:0:604};usage=${DOC:53:32};digest=a0de3;options=(' --abort-ms'\
+trimmed_doc=${DOC:0:678};usage=${DOC:53:32};digest=dd8d3;options=(' --abort-ms'\
 'g 0' ' --auto-reboot 0' ' --no-update 0' ' --no-sb-check 0' ' --no-mount 0' \
-' --repourl 1' ' --install-dev 1' ' --nixosconfig 1');node_0(){ switch \
-__abort_msg 0;};node_1(){ switch __auto_reboot 1;};node_2(){ switch \
-__no_update 2;};node_3(){ switch __no_sb_check 3;};node_4(){ switch __no_mount 4
-};node_5(){ value __repourl 5;};node_6(){ value __install_dev 6;};node_7(){
-value __nixosconfig 7;};node_8(){ optional 0 1 2 3 4 5 6 7;};cat <<<' \
-docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" >&2;printf "%s\n" \
-"${DOC:53:32}" >&2;exit 1;}';local varnames=(__abort_msg __auto_reboot \
-__no_update __no_sb_check __no_mount __repourl __install_dev __nixosconfig) \
-varname;for varname in "${varnames[@]}"; do unset "var_$varname";done;parse 8 \
-"$@";local p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset \
-"$p$varname";done;eval $p'__abort_msg=${var___abort_msg:-false};'$p'__auto_reb'\
-'oot=${var___auto_reboot:-false};'$p'__no_update=${var___no_update:-false};'\
-$p'__no_sb_check=${var___no_sb_check:-false};'$p'__no_mount=${var___no_mount:-'\
-'false};'$p'__repourl=${var___repourl:-'"'"'$REPOURL'"'"'};'$p'__install_dev=$'\
-'{var___install_dev:-};'$p'__nixosconfig=${var___nixosconfig:-};';local \
-docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
-((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare -p \
-"$p$varname";done;done;}
+' --unattended 0' ' --repourl 1' ' --install-dev 1' ' --nixosconfig 1')
+node_0(){ switch __abort_msg 0;};node_1(){ switch __auto_reboot 1;};node_2(){
+switch __no_update 2;};node_3(){ switch __no_sb_check 3;};node_4(){ switch \
+__no_mount 4;};node_5(){ switch __unattended 5;};node_6(){ value __repourl 6;}
+node_7(){ value __install_dev 7;};node_8(){ value __nixosconfig 8;};node_9(){
+optional 0 1 2 3 4 5 6 7 8;};cat <<<' docopt_exit() { [[ -n $1 ]] && printf \
+"%s\n" "$1" >&2;printf "%s\n" "${DOC:53:32}" >&2;exit 1;}';local \
+varnames=(__abort_msg __auto_reboot __no_update __no_sb_check __no_mount \
+__unattended __repourl __install_dev __nixosconfig) varname;for varname in \
+"${varnames[@]}"; do unset "var_$varname";done;parse 9 "$@";local \
+p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset "$p$varname"
+done;eval $p'__abort_msg=${var___abort_msg:-false};'$p'__auto_reboot=${var___a'\
+'uto_reboot:-false};'$p'__no_update=${var___no_update:-false};'$p'__no_sb_chec'\
+'k=${var___no_sb_check:-false};'$p'__no_mount=${var___no_mount:-false};'$p'__u'\
+'nattended=${var___unattended:-false};'$p'__repourl=${var___repourl:-'\
+"'"'$REPOURL'"'"'};'$p'__install_dev=${var___install_dev:-};'$p'__nixosconfig='\
+'${var___nixosconfig:-};';local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && \
+docopt_i=2;for ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; \
+do declare -p "$p$varname";done;done;}
 # docopt parser above, complete command for generating this parser is `docopt.sh --library='"${DOCOPT_LIB_SH:?}/docopt-lib.sh"' installer`
   eval "$(docopt "$@")"
 
@@ -113,31 +116,48 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   $__no_sb_check || sbctl status --json | jq -e .setup_mode >/dev/null 2>&1 || \
     fatal "Your system is not in Setup Mode! Reset secure boot keys so they can be enrolled. You can disable this check with '--no-sb-check'"
 
-  local installdev nixosconfig pwdest
+  local unattended=false installdev nixosconfig hashedpasswordfile hashedpassword enrollfallbackpassword
+  # shellcheck disable=SC2154
+  [[ ! -e $UNATTENDEDPATH ]] || unattended=$__unattended
+  ! $unattended || info "Commencing unattended installation"
   if [[ -n $__install_dev ]]; then
     installdev=$__install_dev
+  elif $unattended; then
+    installdev=$(jq -re .installDev "$UNATTENDEDPATH") || \
+      fatal "Key \"installDev\" missing in %s, unable to continue with unattended install." "$UNATTENDEDPATH"
   else
     installdev=$(get_installdev)
   fi
   if [[ -n $__nixosconfig ]]; then
     nixosconfig=$__nixosconfig
+  elif $unattended; then
+    nixosconfig=$(jq -re .nixOSConfig "$UNATTENDEDPATH") || \
+      fatal "Key \"nixOSConfig\" missing in %s, unable to continue with unattended install." "$UNATTENDEDPATH"
   else
     nixosconfig=$(get_nixosconfig)
   fi
-  recoverykeypath=$(get_config "$nixosconfig" sbfde.recoveryKeyPath | jq -re)
-  enrollemptykey=$(get_config "$nixosconfig" sbfde.enrollEmptyKey | jq -r)
+  if hashedpasswordfile=$(get_config "$nixosconfig" sbfde.hashedPasswordFile | jq -re); then
+    if $unattended; then
+      hashedpassword=$(jq -r '.hashedPassword // empty' "$UNATTENDEDPATH")
+    else
+      get_secret $INSTALLTMP/user_password "Enter your user password"
+      hashedpassword=$(cat $INSTALLTMP/user_password | mkpasswd --stdin)
+    fi
+  fi
   enrollfallbackpassword=$(get_config "$nixosconfig" sbfde.enrollFallbackPassword | jq -r)
-  repartdefinitions=$(nix build "$REPOURL#nixosConfigurations.\"$nixosconfig\".config.sbfde.repartDefinitions" --print-out-paths)
-  ! pwdest=$(get_config "$nixosconfig" sbfde.hashedPasswordFile | jq -re) || \
-    get_secret $INSTALLTMP/user_password "Enter your user password"
-
   if $enrollfallbackpassword; then
+    ! $unattended || fatal "LUKS fallback password enabled. This is unsupported in unattended mode. Disable with sbfde.enrollFallbackPassword=false"
     # Prompt, then prepare enrollment of a fallback FDE password
     (umask 0066; touch $INSTALLTMP/fallback.key)
     get_secret $INSTALLTMP/fallback.key "Enter a disk encryption fallback password"
   else
     rm -f $INSTALLTMP/fallback.key
   fi
+
+  local recoverykeypath enrollemptykey repartdefinitions
+  recoverykeypath=$(get_config "$nixosconfig" sbfde.recoveryKeyPath | jq -re)
+  enrollemptykey=$(get_config "$nixosconfig" sbfde.enrollEmptyKey | jq -r)
+  repartdefinitions=$(nix build "$REPOURL#nixosConfigurations.\"$nixosconfig\".config.sbfde.repartDefinitions" --print-out-paths)
 
   clear
 
@@ -188,12 +208,12 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   info "Installing NixOS"
   nixos-install --verbose --no-root-password --root /mnt --flake "$REPOURL#$nixosconfig"
 
-  if [[ -n $pwdest ]]; then
+  if [[ -n $hashedpasswordfile ]]; then
     info "Copying hashed user password to the system"
-    mkdir -p "$(dirname "/mnt$pwdest")"
-    chmod 755 "$(dirname "/mnt$pwdest")"
-    cat $INSTALLTMP/user_password | mkpasswd --stdin >"/mnt$pwdest"
-    chmod 600 "/mnt$pwdest"
+    mkdir -p "$(dirname "/mnt$hashedpasswordfile")"
+    chmod 755 "$(dirname "/mnt$hashedpasswordfile")"
+    printf "%s" "$hashedpassword" >"/mnt$hashedpasswordfile"
+    chmod 600 "/mnt$hashedpasswordfile"
   fi
 
   # Workaround for lanzaboote not installing the bootloader into the ESP
